export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";
export const REMOVE_SELECTED_TASK_SUCCESS = "REMOVE_SELECTED_TASK_SUCCESS";
